-- Core identity and tenancy tables. Idempotent so it applies cleanly to both fresh databases and
-- databases that were previously created by Hibernate's ddl-auto=update.

CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tuitions (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE,
    name     VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    phone    VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS user_tuition_roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    BIGINT NOT NULL,
    tuition_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    UNIQUE (user_id, tuition_id)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FKq95bjbkh98s6j4lo6gqhfb6c5') THEN
        ALTER TABLE user_tuition_roles ADD CONSTRAINT "FKq95bjbkh98s6j4lo6gqhfb6c5"
            FOREIGN KEY (role_id) REFERENCES roles (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FKk12c6p21ox3dgltmhm0en09yj') THEN
        ALTER TABLE user_tuition_roles ADD CONSTRAINT "FKk12c6p21ox3dgltmhm0en09yj"
            FOREIGN KEY (tuition_id) REFERENCES tuitions (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FKfwd9wnps7piy7asu0dcrex67f') THEN
        ALTER TABLE user_tuition_roles ADD CONSTRAINT "FKfwd9wnps7piy7asu0dcrex67f"
            FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;
END $$;
